// constants/mapKey.js

const GEO_CODER_KEY = 'TFYBZ-KL4KP-PW2DA-VLSVS-WTONK-BVFA6';

const POI_KEY = 'QJ2BZ-42IK2-5BDUW-CQKEO-S5BP5-3EB55';

const CHOOSE_LOCATION_KEY = 'XBGBZ-TD7KW-O5HRH-RXZDA-VPKGV-Z4FSP';

module.exports.GEO_CODER_KEY = GEO_CODER_KEY;
module.exports.POI_KEY = POI_KEY;
module.exports.CHOOSE_LOCATION_KEY = CHOOSE_LOCATION_KEY;